# Generated by Django 3.1.3 on 2020-12-12 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thrifts', '0006_product_is_sold'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('shopping_cart', 'product')},
        ),
    ]
