# Generated by Django 3.1.3 on 2020-12-13 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='rice',
            new_name='price',
        ),
    ]
