# Generated by Django 3.1.3 on 2020-11-29 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='birth',
            field=models.DateField(default=datetime.datetime(2020, 11, 29, 20, 44, 18, 547247)),
            preserve_default=False,
        ),
    ]
