# Generated by Django 3.1.3 on 2020-11-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_details_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='birth',
            field=models.DateField(blank=True),
        ),
    ]
