# Generated by Django 3.1.3 on 2020-11-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201129_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='birth',
            field=models.DateField(null=True),
        ),
    ]
