# Generated by Django 3.1.2 on 2020-10-30 23:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(max_length=200)),
                ('seller', models.CharField(max_length=200)),
                ('comment', models.TextField(blank=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('img', models.ImageField(upload_to='image/')),
                ('description', models.TextField(blank=True)),
                ('seller', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date_posted'],
            },
        ),
    ]
