# Generated by Django 3.1.2 on 2020-10-25 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thrifts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catergory',
            new_name='category',
        ),
    ]
