# Generated by Django 3.1.2 on 2020-10-31 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thrifts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_posted']},
        ),
    ]
