# Generated by Django 3.1.2 on 2020-10-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thrifts', '0002_auto_20201025_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
