# Generated by Django 3.1.2 on 2020-10-31 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thrifts', '0002_auto_20201031_0205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_posted']},
        ),
    ]
