# Generated by Django 3.1.3 on 2020-11-30 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thrifts', '0004_product_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
